import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { ThemeProvider } from "next-themes";
import ClientProvider from "./context/ClientProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <ThemeProvider attribute="class"> */}
      <ThemeProvider attribute="data-theme">
        <body className={montserrat.className}>
          <ClientProvider>
            <Navbar />
            {children}
            <Footer />
          </ClientProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
